# Generated by Django 4.1 on 2023-08-15 04:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollution',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pollution',
            name='location_url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pollution',
            name='image',
            field=models.ImageField(upload_to='images/<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='pollution',
            name='location',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='pollution',
            name='type',
            field=models.CharField(choices=[('grbg', 'Garbage'), ('grpty', 'Graphite'), ('snd', 'Sand')], max_length=10),
        ),
    ]
