# Generated by Django 4.1 on 2023-08-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_pollution_date_pollution_location_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollution',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='pollution',
            name='type',
            field=models.CharField(choices=[('كتابة على الجدران', 'GRAFFITI'), ('لوحات باهتة', 'FADEDـSIGNAGE'), ('لوحات مكسورة', 'BROKEN_SIGNAGE'), ('حفريات', 'POTHOLES'), ('نفايات', 'GARBAGE'), ('طريق بناء', 'CONSTRUCTIONـROAD'), ('إشارة سيئة', 'BADـSTREETLIGHT'), ('لوحة سيئة', 'BADـBILLBOARD'), ('رمال', 'SAND ON ROAD'), ('فوضى جانبية', 'CLUTTER_SIDEWALK'), ('واجهة سيئة', 'UNKEPT_FACADE')], max_length=20),
        ),
    ]
