# Generated by Django 4.1 on 2023-08-17 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_pollution_image_alter_pollution_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pollution',
            unique_together={('location', 'type')},
        ),
    ]
