# Generated by Django 4.1 on 2023-08-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_pollution_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollution',
            name='type',
            field=models.CharField(choices=[('كتابة على الجدران', 'GRAFFITI'), ('لوحة إرشاد باهتة', 'FADEDـSIGNAGE'), ('لوحة إرشاد تالفة', 'BROKEN_SIGNAGE'), ('حفريات', 'POTHOLES'), ('نفايات', 'GARBAGE'), ('أعمال طريق', 'CONSTRUCTIONـROAD'), ('إشارة سيئة', 'BADـSTREETLIGHT'), ('لوحة سيئة', 'BADـBILLBOARD'), ('رمل على الطريق', 'SAND ON ROAD'), ('أرصفة مشوهة', 'CLUTTER_SIDEWALK'), ('واجهة سيئة', 'UNKEPT_FACADE')], max_length=30),
        ),
    ]
